# Generated by Django 2.1.2 on 2018-11-17 22:48

import builtins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'get_latest_by': [builtins.id]},
        ),
    ]
