# Generated by Django 2.1.2 on 2018-11-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages_server', '0002_auto_20181117_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'get_latest_by': ['id']},
        ),
    ]
