# Generated by Django 2.1.2 on 2018-11-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages_server', '0005_auto_20181118_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='group',
            field=models.ManyToManyField(related_name='groups', to='Messages_server.Groups'),
        ),
    ]
